name: android openssl build
on:
  workflow_dispatch:
  push:
    branches:
    - main
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_HOME: emptya
      OPENSSL_DIR: E

    steps: 
      - name: update ubuntu
        run: |
            sudo apt-get update ;

      - name: get openssl src
        run: |
            mkdir -p openssl
            cd openssl
            curl https://www.openssl.org/source/openssl-1.1.1v.tar.gz -o openssl.tar.gz
            tar -xvzf openssl.tar.gz
            cd openssl-1.1.1v
            echo "OPENSSL_DIR=$(pwd)" >> $GITHUB_ENV ;
            echo $OPENSSL_DIR

      - name: get Android NDK
        run: |     
              mkdir -p ndk
              cd ndk
              curl https://dl.google.com/android/repository/android-ndk-r22b-linux-x86_64.zip -o ndk.zip
              unzip ndk.zip
              cd android-ndk-r22b
              echo "ANDROID_NDK_HOME=$(pwd)" >> $GITHUB_ENV ;

      - name: build OPENSSL
        run: |
              date
              cd openssl
              cd openssl-1.1.1v
              ./Configure android-arm shared

              

    
